### ISSUE TITLE
What would it take to run this against http://biorxiv.org/ ?

### ISSUE THREAD

**Issue by danbri** [paperscape/paperscape-backend#1]
If we can get papers in the CSV format you're using, is that enough?

(apologies if this is offtopic for the issue tracker...)

**Comment by dpgeorge** [comment]
The DB of papers in the right format is the first step.  There are some config files that would need adjusting to suit a new DB but they're not hard to configure.  But the main thing is to run the set of papers with the nbody algorithm to lay out the graph and tweak the graph parameters (eg spring force) to make it look good.  That can be difficult and time consuming.

**Comment by danbri** [comment]
Thanks, I'll try to make time to take a look then. I made some experiments in this style previously with Gephi but it was hard to achieve stability between runs of the physics simulations, so I'm interested to see that paperscope has the same consistent 'landscape' layout over time.  Anyway, I'll close out this issue as the core Q is answered, cheers.
