### ISSUE TITLE
Json reference data - what is input-ref-freq?

### ISSUE THREAD

**Issue by ghost** [paperscape/paperscape-backend#3]
In the readme, you describe:
```
[
{"id":input-id,"allcats":"input-category,...","refs":[[input-ref-id,input-ref-freq],...]},
...
]


where input-id, input-ref-id and input-ref-freq are integers, and input-category is a string. Reading in keywords, title and author are currently not supported.
```

What is `input-ref-req`? The number of times a single paper was referenced from this paper?

**Comment by dpgeorge** [comment]
> What is `input-ref-freq`? The number of times a single paper was referenced from this paper?

Yes.  Most papers will reference a paper multiple times in the text (eg in the intro, then in the body a few times, then the conclusion).  Papers that are referenced many times in a single paper are likely the more important ones wrt to the current one (more closely related, or the current paper builds on the previous one).  This metric is very useful in building the graph.

**Comment by ghost** [comment]
Thank you :)
I'm currently doing my second attempt at visualizing the http://us.metamath.org/index.html database using your tools. Thank you for open sourcing it!
